### PR TITLE
Add motivation + various fixups

### PR DESCRIPTION
**Pull request by robpalme**
There's quite a few proposed changes in here.  I'm happy to edit any as you see fit.  The new part is mostly explicit motivation.

### CODE REVIEW

**Review by giltayar — APPROVED** [review]
LGTM

**Review by littledan — APPROVED** [review]
These changes are all excellent. Gil and I have been debating back and forth whether `import type { foo } from "foo"` should have the semantics of `import "foo"` or `/**/`--I wonder if we should note this as an open question. But I'm just going to land this PR and we can iterate more later.

**Comment by robpalme** [comment]
If we want to match TypeScript semantics, the answer is `/**/`.  It's quite important IMO because there needs to be at least one way to achieve type-imports without incurring a runtime import.  And TypeScript already has an answer to that.

**Comment by giltayar** [comment]
Interesting, because I had the same intuition as you, @robpalme. But @littledan convinced me otherwise. His argument was that because we're in JS land, an `import` should _import_ no matter what, and it's weird to have an import that doesn't do anything. If we do what you suggest (and which I wanted to do before Dan convinced me), then it's the only place in the spec where code is "erased".

**Pull request merged**
